services:
  frontend:
    build:
      context: ../frontend/frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ../backend
      dockerfile: target/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app_network
    volumes:
      - ./data:/app/data 
    restart: always

networks:
  app_network:
    driver: bridge